### ISSUE TITLE
Util.js file

### ISSUE THREAD

**Issue by sandytrinh** [linzjs/linz#160]
### Expected behaviour

Ability to invoke javascript code using jQuery in a formtool widget.

### Actual behaviour

Javascript using `linz.addLoadEvent();` throws an error now in the latest tag because the `"/admin/public/js/utils.js` has been moved to the footer.

 `linz.addLoadEvent();` was added to allow queueing of javascript code till jQuery is loaded (in the footer)

### Steps to reproduce the behaviour

1. Create a custom widget a jQuery code snippet
2. Run application
3. Check the Chrome Dev Tool, you'll notice an error that says 'Linz' is undefined. This is because the file that instantiate `linz` have been moved to the footer and is not loaded before the widget code.

**Comment by smebberson** [comment]
@allanchau, we broke something :(

**Comment by sandytrinh** [comment]
Happy to create a PR that moves this JS back to the header if you guys agree?

**Comment by allanchau** [comment]
Oh no I didn't realise that, @sandytrinh @smebberson does that mean the new scripts middleware should be using `linz.addLoadEvent();`?

**Comment by sandytrinh** [comment]
@allanchau I'm not too familiar with the new scripts middleware function, so I can't give any useful comment here :|

**Comment by smebberson** [comment]
@allanchau, nah. `addLoadEvent` and `loadScript` are useful, as Sandy mentions, for working with JavaScript in custom widgets, etc.

So yeah, @sandytrinh, I think it's enough to just pull this small bit of JavaScript back into the head. If you wanted to raise a PR, that'd be sweet :)
