### ISSUE TITLE
Ability to customise different size modal

### ISSUE THREAD

**Issue by sandytrinh** [linzjs/linz#163]
### Expected behaviour

The ability to provide your own HTML for the modal that renders it in different sizes based on the HTML markup. e.g.

`<div class="modal-dialog modal-lg">` renders a large modal

`<div class="modal-dialog">` renders a small model as a default

Check modal [sizes](https://getbootstrap.com/docs/3.3/javascript/#modals-sizes) for more details.

### Actual behaviour

[L68 and L69](https://github.com/linzjs/linz/blob/master/views/layout.jade#L68) of `layout.jade` was added in recent commit which limit the modal to the small size and there's no option to change it to the larger version.

### Suggested change

Remove the 2 line of codes mentioned above and allowing the user to provide a the modal markup. This way user can choose the size they want to use.

**Comment by smebberson** [comment]
@allanchau, any thoughts here?
