### ISSUE TITLE
Permission issue for model listing page

### ISSUE THREAD

**Issue by sandytrinh** [linzjs/linz#169]
### Expected behaviour

A basic model setup like the sample below should render the Edit and Delete button for all views (model index, overview page etc).

```
var linz = require('linz');

// Create a new mongoose schema.
var personSchema = new linz.mongoose.Schema({
  name:  String,
  email: String
});

// Add the Linz formtools plugin.
personSchema.plugin(linz.formtools.plugins.document, {
  model: {
    label: 'Person',
    description: 'A person.',
    title: 'name'
  },
  labels: {
    name: 'Name',
    email: 'Email'
  },
  list: {
    fields: {
      name: true,
      email: true
    }
  },
  form: {
    name: {
      fieldset: 'Details',
      helpText: 'The users full name.'
    },
    email: {
      fieldset: 'Details'
    }
  },
  overview: {
    summary: {
      fields: {
        name: {
          renderer: linz.formtools.cellRenderers.defaultRenderer
        },
        email: {
          renderer: linz.formtools.cellRenderers.defaultRenderer
        }
      }
    }
  },
  fields: {
    usePublishingDate: false,
    usePublishingStatus: false
  }
});

var person = module.exports = linz.mongoose.model('person', personSchema);
```

### Actual behaviour

With the latest tagged version of the code, in the model index page, the Edit and Delete button are omitted by default, unless specific permission settings are included like example below:

```permissions: (user, cb) => cb(null, { canCreate: true, canDelete: true }),```

### Steps to reproduce the behaviour

1. Use example code above in your application code
2. Browse to your model index page in the browser, you should note that there are no Edit and Delete buttons

**Comment by smebberson** [comment]
@sandytrinh, I've confirmed this. It's been fixed in the `add-req` branch. A breaking release which should go out early next week.
